version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - amimart
      - ccamel
    assignees:
      - amimart
      - ccamel
    open-pull-requests-limit: 5
